version: "2"

run:
  timeout: 3m

linters:
  default: standard
  enable:
    - bodyclose
    - dupl
    - errname
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - misspell
    - noctx
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace

linters-settings:
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  revive:
    rules:
      - name: unexported-return
        disabled: true

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
  exclude-dirs:
    - cmd/embed_templates
