// Command claudefilehistory writes cmd/claude_file_history_gen.go: the SHA-256
// of every version of every framework .claude/ file that any cg release has
// shipped, plus the version in the working tree.
//
// `cg sync` uses it to recognise an unedited file in a workspace that cg never
// recorded (one initialised before cg tracked .claude/ files, or whose manifest
// an older binary rewrote). A file matching a shipped version is provably cg's
// own bytes, so it can be updated; anything else is the user's and is left
// alone. Run it through `go generate ./cmd` whenever a .claude/ file changes;
// TestClaudeFileHistoryCoversEmbed fails until you do.
package main

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"flag"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// embedRoots are where the embed tree has lived: templates/ since #131,
// cmd/embed_templates/ in every release before it.
var embedRoots = []string{"templates/", "cmd/embed_templates/"}

// releaseTag matches the tags that produced a published binary.
var releaseTag = regexp.MustCompile(`^v\d+\.\d+\.\d+$`)

// tracked reports whether an embed-relative path is a framework .claude/ file
// source. It is deliberately broader than the install list in cmd/init.go:
// an extra entry costs nothing, while a missing one would make an unedited file
// read as the user's.
func tracked(src string) bool {
	return strings.HasPrefix(src, "commands/") ||
		strings.HasPrefix(src, "skills/") ||
		strings.HasPrefix(src, "workspace/.claude/hooks/") ||
		src == "workspace/.claude/statusline.sh"
}

func main() {
	repo := flag.String("repo", "..", "repository root")
	out := flag.String("o", "claude_file_history_gen.go", "output file")
	flag.Parse()

	hashes := map[string]map[string]bool{}
	add := func(src string, data []byte) {
		sum := sha256.Sum256(data)
		if hashes[src] == nil {
			hashes[src] = map[string]bool{}
		}
		hashes[src][hex.EncodeToString(sum[:])] = true
	}

	tags, err := git(*repo, "tag", "--list", "v*")
	if err != nil {
		fail(err)
	}
	for _, tag := range strings.Fields(string(tags)) {
		if !releaseTag.MatchString(tag) {
			continue
		}
		names, err := git(*repo, "ls-tree", "-r", "--name-only", tag)
		if err != nil {
			fail(err)
		}
		for _, name := range strings.Split(strings.TrimSpace(string(names)), "\n") {
			for _, root := range embedRoots {
				src, ok := strings.CutPrefix(name, root)
				if !ok || !tracked(src) {
					continue
				}
				data, err := git(*repo, "show", tag+":"+name)
				if err != nil {
					fail(err)
				}
				add(src, data)
			}
		}
	}

	// The working tree, so the current (possibly unreleased) version is known
	// too and the guard test can tell the file is up to date.
	root := filepath.Join(*repo, "templates")
	err = filepath.WalkDir(root, func(p string, d fs.DirEntry, werr error) error {
		if werr != nil || d.IsDir() {
			return werr
		}
		rel, rerr := filepath.Rel(root, p)
		if rerr != nil {
			return rerr
		}
		src := filepath.ToSlash(rel)
		if !tracked(src) {
			return nil
		}
		data, rerr := os.ReadFile(p) //nolint:gosec // p comes from walking the repo's own templates/
		if rerr != nil {
			return rerr
		}
		add(src, data)
		return nil
	})
	if err != nil {
		fail(err)
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by scripts/claudefilehistory; DO NOT EDIT.\n\n")
	b.WriteString("package cmd\n\n")
	b.WriteString("// claudeFileHistory maps an embed path to the SHA-256 of every version of\n")
	b.WriteString("// that file a cg release has shipped. Regenerate with `go generate ./cmd`.\n")
	b.WriteString("var claudeFileHistory = map[string][]string{\n")
	srcs := make([]string, 0, len(hashes))
	for src := range hashes {
		srcs = append(srcs, src)
	}
	sort.Strings(srcs)
	for _, src := range srcs {
		sums := make([]string, 0, len(hashes[src]))
		for h := range hashes[src] {
			sums = append(sums, h)
		}
		sort.Strings(sums)
		fmt.Fprintf(&b, "\t%q: {\n", path.Clean(src))
		for _, h := range sums {
			fmt.Fprintf(&b, "\t\t%q,\n", h)
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil { //nolint:gosec // generated source, not a secret
		fail(err)
	}
}

// git runs a git subcommand in repo and returns its stdout.
func git(repo string, args ...string) ([]byte, error) {
	cmd := exec.CommandContext(context.Background(), "git", append([]string{"-C", repo}, args...)...) //nolint:gosec // fixed git subcommands over repo-local refs
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("git %s: %w: %s", strings.Join(args, " "), err, stderr.String())
	}
	return out, nil
}

// fail prints err and exits non-zero.
func fail(err error) {
	fmt.Fprintln(os.Stderr, "claudefilehistory:", err)
	os.Exit(1)
}
