// Code generated by scripts/claudefilehistory; DO NOT EDIT.

package cmd

// claudeFileHistory maps an embed path to the SHA-256 of every version of
// that file a cg release has shipped. Regenerate with `go generate ./cmd`.
var claudeFileHistory = map[string][]string{
	"commands/cg-init.md": {
		"e16866fe70743e0ac0dfb7735689d3e2a80c8c91ba39527695ccbc8e172b69f2",
	},
	"commands/cg-sync.md": {
		"9b14303cc9c6221939cb42f824b91d6e2795e0a6735b554659c0b389275816e0",
		"cde19d55ab23ec20385fb2932dabb85ff1787be49ab4e37aef250bddc58f6d82",
	},
	"commands/match-project.md": {
		"0a90b399c4bad36a910dd7db62430711a1a956ad7b33dee06b21ad597b86b435",
	},
	"skills/wrap/SKILL.md": {
		"168d1dca521f1c34cabd54fa2ef974778de5682d3f7da979bf3815f95b6f069a",
		"3db3643ca0ff9c8ef90d857c7171a575e96f437d6be7174fe6f146a43f08c0cc",
		"703ea036944ca37040ce9eb224ff3a1de2eb88aadd72cbd929156d9ea880e7b4",
		"adc15ba33c42ddef752669b55f5c107d68c056090b3d54feb4cb6305641c6b25",
		"df2f17f33d8404d2fe799f85372f4fb09abad8321638d1645ad74e2fdf3cc57b",
	},
	"workspace/.claude/hooks/external-repo-push-policy.sh": {
		"967c5e7ce87b5f3d380b2121f0ca18c995edf1c6dcbac3faef074da7185493c3",
	},
	"workspace/.claude/hooks/mark-session-dirty.sh": {
		"ec9b87e936864f6d88d61ed18a78b0231a888147901304fdae24c73dfbf8e250",
	},
	"workspace/.claude/hooks/pull-latest-main.sh": {
		"7175179b1acb29e1820ee2cd92d42da47c934c6bac6568c60ad3d31bcc2b7780",
	},
	"workspace/.claude/hooks/session-end.sh": {
		"212d3578ab820e340f254a4c7915bd9d46cfca001fda0cc5094d6989cd24da4a",
	},
	"workspace/.claude/hooks/session-start-gate.sh": {
		"03c58997343d6cce937c735e146e545c80f8997e91a4750f281d7fe07b3950ab",
	},
	"workspace/.claude/statusline.sh": {
		"3aded42eae25a4300e54d431bb2e643e74f7c400fed26828ed7d8b1ce286c7f1",
	},
}
